### PR TITLE
Add SwiftPM support

### PR DESCRIPTION
**Pull request by master-nevi**
* Add Github actions for continuous-integration. Actions will take into affect immediately as shown on my fork: https://github.com/master-nevi/IQDropDownTextField/actions
* Updates .gitignore to ignore some SwiftPM artifacts
* Bump version to `3.1.0`

### CODE REVIEW

**Comment by master-nevi** [comment]
cc @hackiftekhar

**Comment by master-nevi** [comment]
@hackiftekhar any chance you could take a look at this pull request for SPM support? The changes are minor and I even added support for Github Actions.

**Comment by master-nevi** [comment]
@sasojadrovski @hackiftekhar Pinging one more time.

**Comment by master-nevi** [comment]
I guess this library is no longer supported. Will keep this PR open just in case but will probably search for alternatives.

**Comment by hackiftekhar** [comment]
This has been added manually by me. Thanks :)

**Pull request closed without merging**
